package com.mycompany.projeto_poo2;


import com.mycompany.projeto_poo2.dao.ConsultaDAO;
import java.util.List;

// Componentes gráficos
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


// Banco de dados
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Gabriel
 */
public class Tela_De_Consulta extends javax.swing.JFrame {

    /**
     * Creates new form Tela_De_Consulta
     */
    public Tela_De_Consulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Bt_Criar_Consulta = new javax.swing.JButton();
        Bt_Voltar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTable_Historico_Consultas = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_Prescriao = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList_Diagnostico = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton_Prognostico = new javax.swing.JButton();
        jButton_Cadastrar_Prognostico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel3.setText("DIAGNÓSTICO");

        jLabel1.setText("CPF:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JText_Cpf_ConsultaHistorico(evt);
            }
        });

        jButton1.setText("Pesquisar histórico");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_Pesquisa_Historico(evt);
            }
        });

        Bt_Criar_Consulta.setText("Agendar consulta");
        Bt_Criar_Consulta.setToolTipText("");
        Bt_Criar_Consulta.setActionCommand("Criar consulta");
        Bt_Criar_Consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_Criar_ConsultaActionPerformed(evt);
            }
        });

        Bt_Voltar.setText("Voltar");
        Bt_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_VoltarActionPerformed(evt);
            }
        });

        JTable_Historico_Consultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CPF", "NOME", "HORA", "DATA", "MÉDICO"
            }
        ));
        jScrollPane2.setViewportView(JTable_Historico_Consultas);

        jScrollPane1.setViewportView(jList_Prescriao);

        jScrollPane3.setViewportView(jList_Diagnostico);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel4.setText("CONSULTA DE HISTÓRICO DO PACIENTE");

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel5.setText("PRESCRIÇÃO");

        jButton_Prognostico.setText("Pesquisar prognóstico");
        jButton_Prognostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PrognosticoActionPerformed(evt);
            }
        });

        jButton_Cadastrar_Prognostico.setText("Cadastrar prognostico");
        jButton_Cadastrar_Prognostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Cadastrar_PrognosticoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Bt_Voltar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Bt_Criar_Consulta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                                .addComponent(jScrollPane3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_Cadastrar_Prognostico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_Prognostico)))))
                .addGap(45, 45, 45))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(jLabel4)
                    .addContainerGap(646, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(115, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(Bt_Criar_Consulta)
                    .addComponent(Bt_Voltar)
                    .addComponent(jButton_Prognostico)
                    .addComponent(jButton_Cadastrar_Prognostico))
                .addGap(25, 25, 25))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(jLabel4)
                    .addContainerGap(503, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JText_Cpf_ConsultaHistorico(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JText_Cpf_ConsultaHistorico
        // TODO add your handling code here:
    }//GEN-LAST:event_JText_Cpf_ConsultaHistorico

    private void Bt_Pesquisa_Historico(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_Pesquisa_Historico
    String cpf = jTextField1.getText().trim();

    if (cpf.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Informe o CPF do paciente para a consulta.",
                "Erro",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    List<Consulta> historico = new ConsultaDAO().buscarHistoricoPorCpf(cpf);

    if (historico.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Nenhum histórico encontrado para o CPF informado.",
            "Aviso",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
       }

       // Preenche a jTable1
javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) JTable_Historico_Consultas.getModel();
modelo.setRowCount(0); // limpa tabela

for (Consulta consulta : historico) {
    modelo.addRow(new Object[]{
        consulta.getPaciente().getCpf(),
        consulta.getPaciente().getNome(),
        consulta.getHora(),
        consulta.getData(),
        consulta.getMedico().getNome()
    });
}
    }//GEN-LAST:event_Bt_Pesquisa_Historico

    private void Bt_Criar_ConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_Criar_ConsultaActionPerformed
    // Cria uma nova instância da tela de consulta
    FTela_Agendamento tela = new FTela_Agendamento();
    
    // Torna a tela visível
    tela.setVisible(true);
    
    }//GEN-LAST:event_Bt_Criar_ConsultaActionPerformed

    private void Bt_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_VoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_Bt_VoltarActionPerformed

    private void jButton_PrognosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PrognosticoActionPerformed

    DefaultListModel<String> modeloDiagnostico = new DefaultListModel<>();
    DefaultListModel<String> modeloPrescricao = new DefaultListModel<>();

    int linhaSelecionada = JTable_Historico_Consultas.getSelectedRow();

    if (linhaSelecionada != -1) {
        String cpf = JTable_Historico_Consultas.getValueAt(linhaSelecionada, 0).toString();
        String data = JTable_Historico_Consultas.getValueAt(linhaSelecionada, 3).toString();
        String hora = JTable_Historico_Consultas.getValueAt(linhaSelecionada, 2).toString();

        try {
            Connection conexao = com.mycompany.projeto_poo2.dao.Conexao.getConection();
            String sql = "SELECT diagnostico, prescricoes FROM consulta WHERE cpf = ? AND data = ? AND hora = ?";
            PreparedStatement ps = conexao.prepareStatement(sql);
            ps.setString(1, cpf);
            ps.setString(2, data);
            ps.setString(3, hora);

            ResultSet rs = ps.executeQuery();

            modeloDiagnostico.clear();
            modeloPrescricao.clear();

            if (rs.next()) {
                String diagnostico = rs.getString("diagnostico");
                String prescricao = rs.getString("prescricoes");

                modeloDiagnostico.addElement(
                    (diagnostico != null && !diagnostico.isEmpty()) ? diagnostico : "Nenhum diagnóstico cadastrado."
                );

                modeloPrescricao.addElement(
                    (prescricao != null && !prescricao.isEmpty()) ? prescricao : "Nenhuma prescrição cadastrada."
                );

            } else {
                JOptionPane.showMessageDialog(this, "Nenhum prognóstico encontrado para essa consulta.");
                modeloDiagnostico.addElement("Nenhum diagnóstico encontrado.");
                modeloPrescricao.addElement("Nenhuma prescrição encontrada.");
            }

            jList_Diagnostico.setModel(modeloDiagnostico);
            jList_Prescriao.setModel(modeloPrescricao);

            rs.close();
            ps.close();
            conexao.close();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao buscar prognóstico: " + ex.getMessage());
            ex.printStackTrace();
        }

    } else {
        JOptionPane.showMessageDialog(this, "Selecione uma consulta na tabela primeiro.");
    }
    }//GEN-LAST:event_jButton_PrognosticoActionPerformed

    private void jButton_Cadastrar_PrognosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Cadastrar_PrognosticoActionPerformed

    }//GEN-LAST:event_jButton_Cadastrar_PrognosticoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_De_Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_De_Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_De_Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_De_Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_De_Consulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_Criar_Consulta;
    private javax.swing.JButton Bt_Voltar;
    private javax.swing.JTable JTable_Historico_Consultas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Cadastrar_Prognostico;
    private javax.swing.JButton jButton_Prognostico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList_Diagnostico;
    private javax.swing.JList<String> jList_Prescriao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
